name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # or 'main' if that's your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Add Node.js version specification at the job level
    defaults:
      run:
        shell: bash
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Update Node.js setup to ensure version 20
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Explicitly use Node 20 LTS
          cache: 'npm'

      # Clean install to avoid cache issues
      - name: Install Dependencies
        run: |
          npm ci --no-audit
          # Alternative if ci fails:
          # rm -rf node_modules package-lock.json
          # npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
